name = "OSReconstruction"
version = "0.1.0"
defaultTargets = ["OSReconstruction"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "6dc31c12d6ffdc9a63ebddee67264ea348cc06f8"

[[require]]
name = "GaussianField"
git = "https://github.com/mrdouglasny/gaussian-field.git"
rev = "main"
subDir = "."

[[lean_lib]]
name = "OSReconstruction"
