name = "OSReconstruction"
version = "0.1.0"
defaultTargets = ["OSReconstruction"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[require]]
name = "GaussianField"
git = "https://github.com/mrdouglasny/gaussian-field.git"
rev = "c2d47b72dd0757b6a4e0a4139d3841ead6c4f4a8"
subDir = "."

[[lean_lib]]
name = "OSReconstruction"
