name = "OSReconstruction"
version = "0.1.0"
defaultTargets = ["OSReconstruction"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0-rc1"

[[require]]
name = "GaussianField"
git = "https://github.com/mrdouglasny/gaussian-field.git"
rev = "main"
subDir = "."

[[require]]
name = "Dress"
git = "https://github.com/e-vergo/Dress.git"
rev = "main"

[[lean_lib]]
name = "OSReconstruction"
